parameters:
    # Main theme.
    f0ska.autogrid.template.theme: '@@F0skaAutoGrid/bootstrap_5'
    f0ska.autogrid.template.form_themes: [ 'bootstrap_5_layout.html.twig' ]

    # Base templates
    f0ska.autogrid.template.base: 'base.html.twig'

    # Action templates
    f0ska.autogrid.template.action.grid: 'action/grid.html.twig'
    f0ska.autogrid.template.action.form: 'action/form.html.twig'
    f0ska.autogrid.template.action.view: 'action/view.html.twig'
    f0ska.autogrid.template.action.error: 'action/error.html.twig'

    # Field type templates.
    f0ska.autogrid.template.field.debug: 'field/debug.html.twig'
    f0ska.autogrid.template.field.text: 'field/text.html.twig'
    f0ska.autogrid.template.field.date: 'field/date.html.twig'
    f0ska.autogrid.template.field.choice: 'field/choice.html.twig'
    f0ska.autogrid.template.field.boolean: 'field/boolean.html.twig'
    f0ska.autogrid.template.field.simple_array: 'field/array.html.twig'
    f0ska.autogrid.template.field.json: 'field/json.html.twig'
    f0ska.autogrid.template.field.ascii_string: 'field/ascii.html.twig'
    f0ska.autogrid.template.field.binary: 'field/binary.html.twig'

    # Fieldset templates.
    f0ska.autogrid.template.fieldset.view: 'fieldset/view.html.twig'
    f0ska.autogrid.template.fieldset.form: 'fieldset/form.html.twig'

    # Grid parts.
    f0ska.autogrid.template.grid.advanced_filter: 'grid/advanced_filter.html.twig'
    f0ska.autogrid.template.grid.column_header: 'grid/column_header.html.twig'
    f0ska.autogrid.template.grid.column_header_action: 'grid/column_header_action.html.twig'
    f0ska.autogrid.template.grid.column_header_filter: 'grid/column_header_filter.html.twig'
    f0ska.autogrid.template.grid.column_header_massaction: 'grid/column_header_massaction.html.twig'
    f0ska.autogrid.template.grid.column_header_sort: 'grid/column_header_sort.html.twig'
    f0ska.autogrid.template.grid.column_value: 'grid/column_value.html.twig'
    f0ska.autogrid.template.grid.column_value_action: 'grid/column_value_action.html.twig'
    f0ska.autogrid.template.grid.column_value_massaction: 'grid/column_value_massaction.html.twig'
    f0ska.autogrid.template.grid.grid_number_per_page: 'grid/grid_number_per_page.html.twig'
    f0ska.autogrid.template.grid.grid_pagiantion: 'grid/grid_pagiantion.html.twig'
    f0ska.autogrid.template.grid.row_class: 'grid/row_class.html.twig'

    # Date formats for the data view (not for a form field)
    f0ska.autogrid.view.field.format.date: 'Y-m-d'
    f0ska.autogrid.view.field.format.time: 'H:i'
    f0ska.autogrid.view.field.format.datetime: 'Y-m-d H:i'
    f0ska.autogrid.view.field.format.interval: '%Yy, %mm, %dd'

    # Display settings.
    f0ska.autogrid.view.friendly_id: 'autogrid' # Used for frontend container id, class and link fragment generation.
    f0ska.autogrid.grid.pagination_limits: [ 10, 50, 100 ] # Set it with a single value to remove grid limit selector.
    f0ska.autogrid.grid.text.truncate: 55 # Maximal content length in grid cell.
    f0ska.autogrid.common.show_entity_title: true # Just a grid title.

    # Basic action buttons display.
    f0ska.autogrid.grid.view_button_in_grid: true
    f0ska.autogrid.grid.view_button_in_edit: true
    f0ska.autogrid.grid.edit_button_in_grid: true
    f0ska.autogrid.grid.edit_button_in_view: true
    f0ska.autogrid.grid.delete_button_in_grid: true
    f0ska.autogrid.grid.delete_button_in_view: true
    f0ska.autogrid.grid.delete_button_in_edit: true

    # Request parameters setting
    f0ska.autogrid.request.single_parameter_mode: false # Store all url parameters in single request parameter (base64).
    f0ska.autogrid.request.single_parameter_code: '_ag'
    f0ska.autogrid.request.parameter_code.id: 'agId' # Instance identifier.
    f0ska.autogrid.request.parameter_code.action: 'agAction' # Current action.
    f0ska.autogrid.request.parameter_code.params: 'agParams' # Current action parameters.

    # Enable this for better experience on multiple grid pages.
    f0ska.autogrid.store_navigation_in_session: true

    # By default, render boolean as select (if no form options defined).
    f0ska.autogrid.form.default_boolean_as_select: false
    # By default, render all date filter as "range". Overrides by RangeFilter attribute.
    f0ska.autogrid.form.default_date_filter_range: true
